# fly.toml app configuration file generated for playbuddy-api on 2025-08-10T11:02:14-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'playbuddy-api'
primary_region = 'iad'

[build]

[processes]
  app = "node ./dist/app.js"
  large = "node ./dist/app.js"

[[services]]
  processes = ['app']
  internal_port = 8080
  protocol = "tcp"

  # Keep the machine warm; no scale-to-zero
  auto_start_machines = true
  auto_stop_machines  = false
  min_machines_running = 1

  # Still good to have limits to protect the instance
  [services.concurrency]
    type = "requests"
    soft_limit = 40
    hard_limit = 80

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[services]]
  processes = ['large']
  internal_port = 8080
  protocol = "tcp"

  # On-demand large machines should scale to zero.
  auto_start_machines = true
  auto_stop_machines  = true
  min_machines_running = 0
  max_machines_running = 1

  [services.concurrency]
    type = "requests"
    soft_limit = 40
    hard_limit = 80

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[vm]]
  processes = ['app']
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[vm]]
  processes = ['large']
  memory = '32gb'
  cpu_kind = 'performance'
  cpus = 8
